# Let's Plot Some Graphs 
# Based on the answer from Enke @ StackOverflow 
# https://stackoverflow.com/questions/71001130/calculating-percentages-for-multiple-columns?noredirect=1#comment125515642_71001130

#import libraries
import pandas as pd 
import plotly.express as px 

# read .csv file from github. File was generated by aggregator.py

df = pd.read_csv('https://raw.githubusercontent.com/JorgeMiguelGomes/LEG2022_MediaMonitor/main/legislativas_2022_media_monitor_29jan2022/data_products/legislativas_2022_all_candidates_filtered.csv')

df = df.drop(columns=["Unnamed: 0"])

# define totals per column 
totals = df.groupby(['Page Name','candidato'])[['Total Interactions','Likes','Comments','Shares','Love','Angry']].sum()
#calculate percentages for each column 
percentages = totals.groupby(level=0).transform('sum').rdiv(totals).mul(100).round(2)

# create dataframe from both dataframes 

df_final = totals.join(percentages, lsuffix='', rsuffix='_Percentages').reset_index()


df_final.to_csv('../data_products/legislativas_2022_final_dataset_percentages.csv')

print(df_final.head())

# Create color for each candidate 

candidate_color_map = {
    "Rui Rio": "#FF6400",
    "Francisco Rodrigues dos Santos": "#0B6AB1",
    "António Costa": "#F1A0A2",
    "Rui Tavares": "#00CE8C",
    "Catarina Martins": "#C90635",
    "Jerónimo de Sousa": "#025298",
    "André Ventura": "#202056",
    "João Cotrim Figueiredo": "#00AEEF",
    "Inês Sousa-Real": "#00798E"
}


# Percent Stacked Bar Chart Total Interactions 

stack_total = px.bar(df_final,x='Page Name',y='Total Interactions_Percentages',color='candidato',color_discrete_map=candidate_color_map)
stack_total.show()
